<?php

namespace WebimpressTest\PHPUnitMigration\Migration\TestAsset;

use PHPUnit\Framework\TestCase;

class VoidReturnTypeMigration extends TestCase
{
    public function setUp()
    {
    }

    protected function tearDown()
    {
    }

    public static function setUpBeforeClass()
    {
    }

    public static function tearDownAfterClass()
    {
    }

    protected function assertPreConditions() {}

    protected function assertPostConditions() {}

    protected function onNotSuccessfulTest(\Throwable $t) {}
}
